[2024-04-19 17:19:50,536] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:19:49.411435+00:00 [queued]>
[2024-04-19 17:19:50,548] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:19:49.411435+00:00 [queued]>
[2024-04-19 17:19:50,548] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:19:50,549] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 17:19:50,549] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:19:50,564] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-19 17:19:49.411435+00:00
[2024-04-19 17:19:50,568] {standard_task_runner.py:52} INFO - Started process 787 to run task
[2024-04-19 17:19:50,571] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'manual__2024-04-19T17:19:49.411435+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpbro2f1v0', '--error-file', '/tmp/tmp9jub2bde']
[2024-04-19 17:19:50,572] {standard_task_runner.py:80} INFO - Job 66: Subtask notificar_objetos_cercanos
[2024-04-19 17:19:50,662] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:19:49.411435+00:00 [running]> on host 2e237166a7ec
[2024-04-19 17:19:50,738] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-19T17:19:49.411435+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-19T17:19:49.411435+00:00
[2024-04-19 17:19:53,011] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials f15-20020a170902ce8f00b001dde004b31bsm3596412plg.166 - gsmtp')
[2024-04-19 17:19:53,012] {logging_mixin.py:115} INFO - Failure
[2024-04-19 17:19:53,012] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 17:19:53,029] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240419T171949, start_date=20240419T171950, end_date=20240419T171953
[2024-04-19 17:19:53,084] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 17:19:53,116] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
