[2024-04-09 21:22:06,293] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T21:19:00.940661+00:00 [queued]>
[2024-04-09 21:22:06,305] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T21:19:00.940661+00:00 [queued]>
[2024-04-09 21:22:06,307] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:22:06,308] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2024-04-09 21:22:06,309] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:22:06,324] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): Descargar_datos_crudos> on 2024-04-09 21:19:00.940661+00:00
[2024-04-09 21:22:06,331] {standard_task_runner.py:52} INFO - Started process 491 to run task
[2024-04-09 21:22:06,333] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'Descargar_datos_crudos', 'manual__2024-04-09T21:19:00.940661+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpef44kwgv', '--error-file', '/tmp/tmpniyvgprc']
[2024-04-09 21:22:06,335] {standard_task_runner.py:80} INFO - Job 96: Subtask Descargar_datos_crudos
[2024-04-09 21:22:06,402] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T21:19:00.940661+00:00 [running]> on host c346f321fefe
[2024-04-09 21:22:06,471] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=Descargar_datos_crudos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-09T21:19:00.940661+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-09T21:19:00.940661+00:00
[2024-04-09 21:22:06,473] {logging_mixin.py:115} INFO - Hola
[2024-04-09 21:22:07,299] {logging_mixin.py:115} INFO - <Response [200]>
[2024-04-09 21:22:07,300] {python.py:173} INFO - Done. Returned value was: <Response [200]>
[2024-04-09 21:22:07,306] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-04-09 21:22:07,307] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2024-04-09 21:22:07,315] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=NEO_coderhouse, task_id=Descargar_datos_crudos, execution_date=20240409T211900, start_date=20240409T212206, end_date=20240409T212207
[2024-04-09 21:22:07,326] {standard_task_runner.py:97} ERROR - Failed to execute job 96 for task Descargar_datos_crudos (Object of type Response is not JSON serializable; 491)
[2024-04-09 21:22:07,353] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-09 21:22:07,389] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
