[2024-04-19 17:11:50,847] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:11:49.639411+00:00 [queued]>
[2024-04-19 17:11:50,857] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:11:49.639411+00:00 [queued]>
[2024-04-19 17:11:50,858] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:11:50,859] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 17:11:50,860] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:11:50,876] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-19 17:11:49.639411+00:00
[2024-04-19 17:11:50,880] {standard_task_runner.py:52} INFO - Started process 508 to run task
[2024-04-19 17:11:50,884] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'manual__2024-04-19T17:11:49.639411+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpj3y1haqh', '--error-file', '/tmp/tmpcw8i3dwg']
[2024-04-19 17:11:50,885] {standard_task_runner.py:80} INFO - Job 65: Subtask notificar_objetos_cercanos
[2024-04-19 17:11:50,963] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:11:49.639411+00:00 [running]> on host 2e237166a7ec
[2024-04-19 17:11:51,027] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-19T17:11:49.639411+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-19T17:11:49.639411+00:00
[2024-04-19 17:11:53,178] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials s23-20020a63dc17000000b005f77433b4f9sm3359088pgg.81 - gsmtp')
[2024-04-19 17:11:53,179] {logging_mixin.py:115} INFO - Failure
[2024-04-19 17:11:53,179] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 17:11:53,195] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240419T171149, start_date=20240419T171150, end_date=20240419T171153
[2024-04-19 17:11:53,234] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 17:11:53,269] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
