[2024-04-19 17:06:57,835] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:06:56.489950+00:00 [queued]>
[2024-04-19 17:06:57,845] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:06:56.489950+00:00 [queued]>
[2024-04-19 17:06:57,846] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:06:57,847] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 17:06:57,848] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:06:57,862] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-19 17:06:56.489950+00:00
[2024-04-19 17:06:57,867] {standard_task_runner.py:52} INFO - Started process 337 to run task
[2024-04-19 17:06:57,870] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'manual__2024-04-19T17:06:56.489950+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu_bkz51n', '--error-file', '/tmp/tmpecw8bvny']
[2024-04-19 17:06:57,871] {standard_task_runner.py:80} INFO - Job 64: Subtask notificar_objetos_cercanos
[2024-04-19 17:06:57,935] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:06:56.489950+00:00 [running]> on host 2e237166a7ec
[2024-04-19 17:06:58,005] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-19T17:06:56.489950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-19T17:06:56.489950+00:00
[2024-04-19 17:06:59,908] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials q4-20020a170902edc400b001e29c4b7bd2sm3582121plk.240 - gsmtp')
[2024-04-19 17:06:59,910] {logging_mixin.py:115} INFO - Failure
[2024-04-19 17:06:59,911] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 17:06:59,928] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240419T170656, start_date=20240419T170657, end_date=20240419T170659
[2024-04-19 17:06:59,979] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 17:07:00,010] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
