[2024-04-19 17:21:58,722] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:21:57.722469+00:00 [queued]>
[2024-04-19 17:21:58,732] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:21:57.722469+00:00 [queued]>
[2024-04-19 17:21:58,733] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:21:58,734] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 17:21:58,734] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 17:21:58,750] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-19 17:21:57.722469+00:00
[2024-04-19 17:21:58,754] {standard_task_runner.py:52} INFO - Started process 862 to run task
[2024-04-19 17:21:58,757] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'manual__2024-04-19T17:21:57.722469+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4p6chj1n', '--error-file', '/tmp/tmp1uk4_49c']
[2024-04-19 17:21:58,758] {standard_task_runner.py:80} INFO - Job 67: Subtask notificar_objetos_cercanos
[2024-04-19 17:21:58,816] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T17:21:57.722469+00:00 [running]> on host 2e237166a7ec
[2024-04-19 17:21:58,883] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-19T17:21:57.722469+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-19T17:21:57.722469+00:00
[2024-04-19 17:22:00,842] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials y14-20020a1709027c8e00b001e3e244e5c0sm3586889pll.78 - gsmtp')
[2024-04-19 17:22:00,843] {logging_mixin.py:115} INFO - Failure
[2024-04-19 17:22:00,843] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 17:22:00,858] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240419T172157, start_date=20240419T172158, end_date=20240419T172200
[2024-04-19 17:22:00,906] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 17:22:00,938] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
