[2024-04-19 16:45:39,995] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T16:45:39.076137+00:00 [queued]>
[2024-04-19 16:45:40,007] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T16:45:39.076137+00:00 [queued]>
[2024-04-19 16:45:40,007] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:45:40,008] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-04-19 16:45:40,009] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-19 16:45:40,031] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): notificar_objetos_cercanos> on 2024-04-19 16:45:39.076137+00:00
[2024-04-19 16:45:40,035] {standard_task_runner.py:52} INFO - Started process 256 to run task
[2024-04-19 16:45:40,038] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'notificar_objetos_cercanos', 'manual__2024-04-19T16:45:39.076137+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmxni7grf', '--error-file', '/tmp/tmpcrpr3zup']
[2024-04-19 16:45:40,039] {standard_task_runner.py:80} INFO - Job 61: Subtask notificar_objetos_cercanos
[2024-04-19 16:45:40,107] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.notificar_objetos_cercanos manual__2024-04-19T16:45:39.076137+00:00 [running]> on host 2e237166a7ec
[2024-04-19 16:45:40,175] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=notificar_objetos_cercanos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-19T16:45:39.076137+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-19T16:45:39.076137+00:00
[2024-04-19 16:45:42,261] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials y24-20020aa78558000000b006ecfb06413dsm3437291pfn.197 - gsmtp')
[2024-04-19 16:45:42,262] {logging_mixin.py:115} INFO - Failure
[2024-04-19 16:45:42,262] {python.py:173} INFO - Done. Returned value was: None
[2024-04-19 16:45:42,273] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=NEO_coderhouse, task_id=notificar_objetos_cercanos, execution_date=20240419T164539, start_date=20240419T164539, end_date=20240419T164542
[2024-04-19 16:45:42,306] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-04-19 16:45:42,338] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
